// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: service/gateway.proto

package service

import (
	helium "github.com/dougkirkley/helium-go/internal/helium"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CloseState int32

const (
	CloseState_close_state_closable CloseState = 0
	CloseState_close_state_closing  CloseState = 1
	CloseState_close_state_closed   CloseState = 2
	CloseState_close_state_dispute  CloseState = 3
)

// Enum value maps for CloseState.
var (
	CloseState_name = map[int32]string{
		0: "close_state_closable",
		1: "close_state_closing",
		2: "close_state_closed",
		3: "close_state_dispute",
	}
	CloseState_value = map[string]int32{
		"close_state_closable": 0,
		"close_state_closing":  1,
		"close_state_closed":   2,
		"close_state_dispute":  3,
	}
)

func (x CloseState) Enum() *CloseState {
	p := new(CloseState)
	*p = x
	return p
}

func (x CloseState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloseState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateway_proto_enumTypes[0].Descriptor()
}

func (CloseState) Type() protoreflect.EnumType {
	return &file_service_gateway_proto_enumTypes[0]
}

func (x CloseState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloseState.Descriptor instead.
func (CloseState) EnumDescriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{0}
}

type GatewayRespV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are assignable to Msg:
	//	*GatewayRespV1_IsValidResp
	//	*GatewayRespV1_CloseResp
	//	*GatewayRespV1_FollowStreamedResp
	//	*GatewayRespV1_RoutingStreamedResp
	Msg isGatewayRespV1_Msg `protobuf_oneof:"msg"`
}

func (x *GatewayRespV1) Reset() {
	*x = GatewayRespV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayRespV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRespV1) ProtoMessage() {}

func (x *GatewayRespV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRespV1.ProtoReflect.Descriptor instead.
func (*GatewayRespV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayRespV1) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *GatewayRespV1) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (m *GatewayRespV1) GetMsg() isGatewayRespV1_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *GatewayRespV1) GetIsValidResp() *GatewayScIsValidRespV1 {
	if x, ok := x.GetMsg().(*GatewayRespV1_IsValidResp); ok {
		return x.IsValidResp
	}
	return nil
}

func (x *GatewayRespV1) GetCloseResp() *GatewayScCloseRespV1 {
	if x, ok := x.GetMsg().(*GatewayRespV1_CloseResp); ok {
		return x.CloseResp
	}
	return nil
}

func (x *GatewayRespV1) GetFollowStreamedResp() *GatewayScFollowStreamedRespV1 {
	if x, ok := x.GetMsg().(*GatewayRespV1_FollowStreamedResp); ok {
		return x.FollowStreamedResp
	}
	return nil
}

func (x *GatewayRespV1) GetRoutingStreamedResp() *GatewayRoutingStreamedRespV1 {
	if x, ok := x.GetMsg().(*GatewayRespV1_RoutingStreamedResp); ok {
		return x.RoutingStreamedResp
	}
	return nil
}

type isGatewayRespV1_Msg interface {
	isGatewayRespV1_Msg()
}

type GatewayRespV1_IsValidResp struct {
	IsValidResp *GatewayScIsValidRespV1 `protobuf:"bytes,3,opt,name=is_valid_resp,json=isValidResp,proto3,oneof"`
}

type GatewayRespV1_CloseResp struct {
	CloseResp *GatewayScCloseRespV1 `protobuf:"bytes,4,opt,name=close_resp,json=closeResp,proto3,oneof"`
}

type GatewayRespV1_FollowStreamedResp struct {
	FollowStreamedResp *GatewayScFollowStreamedRespV1 `protobuf:"bytes,5,opt,name=follow_streamed_resp,json=followStreamedResp,proto3,oneof"`
}

type GatewayRespV1_RoutingStreamedResp struct {
	RoutingStreamedResp *GatewayRoutingStreamedRespV1 `protobuf:"bytes,6,opt,name=routing_streamed_resp,json=routingStreamedResp,proto3,oneof"`
}

func (*GatewayRespV1_IsValidResp) isGatewayRespV1_Msg() {}

func (*GatewayRespV1_CloseResp) isGatewayRespV1_Msg() {}

func (*GatewayRespV1_FollowStreamedResp) isGatewayRespV1_Msg() {}

func (*GatewayRespV1_RoutingStreamedResp) isGatewayRespV1_Msg() {}

type GatewayScIsValidReqV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sc *helium.BlockchainStateChannelV1 `protobuf:"bytes,1,opt,name=sc,proto3" json:"sc,omitempty"`
}

func (x *GatewayScIsValidReqV1) Reset() {
	*x = GatewayScIsValidReqV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayScIsValidReqV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScIsValidReqV1) ProtoMessage() {}

func (x *GatewayScIsValidReqV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScIsValidReqV1.ProtoReflect.Descriptor instead.
func (*GatewayScIsValidReqV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GatewayScIsValidReqV1) GetSc() *helium.BlockchainStateChannelV1 {
	if x != nil {
		return x.Sc
	}
	return nil
}

type GatewayScIsValidRespV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId   []byte `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	Valid  bool   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Reason []byte `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *GatewayScIsValidRespV1) Reset() {
	*x = GatewayScIsValidRespV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayScIsValidRespV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScIsValidRespV1) ProtoMessage() {}

func (x *GatewayScIsValidRespV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScIsValidRespV1.ProtoReflect.Descriptor instead.
func (*GatewayScIsValidRespV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *GatewayScIsValidRespV1) GetScId() []byte {
	if x != nil {
		return x.ScId
	}
	return nil
}

func (x *GatewayScIsValidRespV1) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *GatewayScIsValidRespV1) GetReason() []byte {
	if x != nil {
		return x.Reason
	}
	return nil
}

type GatewayScCloseReqV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CloseTxn *helium.BlockchainTxnStateChannelCloseV1 `protobuf:"bytes,1,opt,name=close_txn,json=closeTxn,proto3" json:"close_txn,omitempty"`
}

func (x *GatewayScCloseReqV1) Reset() {
	*x = GatewayScCloseReqV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayScCloseReqV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScCloseReqV1) ProtoMessage() {}

func (x *GatewayScCloseReqV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScCloseReqV1.ProtoReflect.Descriptor instead.
func (*GatewayScCloseReqV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GatewayScCloseReqV1) GetCloseTxn() *helium.BlockchainTxnStateChannelCloseV1 {
	if x != nil {
		return x.CloseTxn
	}
	return nil
}

type GatewayScCloseRespV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId     []byte `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	Response []byte `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *GatewayScCloseRespV1) Reset() {
	*x = GatewayScCloseRespV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayScCloseRespV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScCloseRespV1) ProtoMessage() {}

func (x *GatewayScCloseRespV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScCloseRespV1.ProtoReflect.Descriptor instead.
func (*GatewayScCloseRespV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayScCloseRespV1) GetScId() []byte {
	if x != nil {
		return x.ScId
	}
	return nil
}

func (x *GatewayScCloseRespV1) GetResponse() []byte {
	if x != nil {
		return x.Response
	}
	return nil
}

type GatewayScFollowReqV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId  []byte `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	Owner []byte `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (x *GatewayScFollowReqV1) Reset() {
	*x = GatewayScFollowReqV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayScFollowReqV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScFollowReqV1) ProtoMessage() {}

func (x *GatewayScFollowReqV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScFollowReqV1.ProtoReflect.Descriptor instead.
func (*GatewayScFollowReqV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GatewayScFollowReqV1) GetScId() []byte {
	if x != nil {
		return x.ScId
	}
	return nil
}

func (x *GatewayScFollowReqV1) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

type GatewayScFollowStreamedRespV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScId       []byte     `protobuf:"bytes,1,opt,name=sc_id,json=scId,proto3" json:"sc_id,omitempty"`
	CloseState CloseState `protobuf:"varint,2,opt,name=close_state,json=closeState,proto3,enum=helium.CloseState" json:"close_state,omitempty"`
}

func (x *GatewayScFollowStreamedRespV1) Reset() {
	*x = GatewayScFollowStreamedRespV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayScFollowStreamedRespV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayScFollowStreamedRespV1) ProtoMessage() {}

func (x *GatewayScFollowStreamedRespV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayScFollowStreamedRespV1.ProtoReflect.Descriptor instead.
func (*GatewayScFollowStreamedRespV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *GatewayScFollowStreamedRespV1) GetScId() []byte {
	if x != nil {
		return x.ScId
	}
	return nil
}

func (x *GatewayScFollowStreamedRespV1) GetCloseState() CloseState {
	if x != nil {
		return x.CloseState
	}
	return CloseState_close_state_closable
}

type Routing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oui       uint32            `protobuf:"varint,1,opt,name=oui,proto3" json:"oui,omitempty"`
	Owner     []byte            `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Addresses []*RoutingAddress `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Filters   [][]byte          `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	Subnets   [][]byte          `protobuf:"bytes,5,rep,name=subnets,proto3" json:"subnets,omitempty"`
}

func (x *Routing) Reset() {
	*x = Routing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Routing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routing) ProtoMessage() {}

func (x *Routing) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routing.ProtoReflect.Descriptor instead.
func (*Routing) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *Routing) GetOui() uint32 {
	if x != nil {
		return x.Oui
	}
	return 0
}

func (x *Routing) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Routing) GetAddresses() []*RoutingAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *Routing) GetFilters() [][]byte {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *Routing) GetSubnets() [][]byte {
	if x != nil {
		return x.Subnets
	}
	return nil
}

type RoutingAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PubKey []byte `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	Uri    []byte `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *RoutingAddress) Reset() {
	*x = RoutingAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingAddress) ProtoMessage() {}

func (x *RoutingAddress) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingAddress.ProtoReflect.Descriptor instead.
func (*RoutingAddress) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *RoutingAddress) GetPubKey() []byte {
	if x != nil {
		return x.PubKey
	}
	return nil
}

func (x *RoutingAddress) GetUri() []byte {
	if x != nil {
		return x.Uri
	}
	return nil
}

type GatewayRoutingReqV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *GatewayRoutingReqV1) Reset() {
	*x = GatewayRoutingReqV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayRoutingReqV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRoutingReqV1) ProtoMessage() {}

func (x *GatewayRoutingReqV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRoutingReqV1.ProtoReflect.Descriptor instead.
func (*GatewayRoutingReqV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayRoutingReqV1) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type GatewayRoutingStreamedRespV1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Routings []*Routing `protobuf:"bytes,1,rep,name=routings,proto3" json:"routings,omitempty"`
}

func (x *GatewayRoutingStreamedRespV1) Reset() {
	*x = GatewayRoutingStreamedRespV1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_gateway_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayRoutingStreamedRespV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayRoutingStreamedRespV1) ProtoMessage() {}

func (x *GatewayRoutingStreamedRespV1) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateway_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayRoutingStreamedRespV1.ProtoReflect.Descriptor instead.
func (*GatewayRoutingStreamedRespV1) Descriptor() ([]byte, []int) {
	return file_service_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayRoutingStreamedRespV1) GetRoutings() []*Routing {
	if x != nil {
		return x.Routings
	}
	return nil
}

var File_service_gateway_proto protoreflect.FileDescriptor

var file_service_gateway_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x1a,
	0x21, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x2b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74,
	0x78, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x76, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9c, 0x03, 0x0a, 0x0f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x5f, 0x76, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x49, 0x0a, 0x0d, 0x69, 0x73, 0x5f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61,
	0x79, 0x5f, 0x73, 0x63, 0x5f, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x76, 0x31, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76, 0x31, 0x48, 0x00, 0x52, 0x09, 0x63, 0x6c,
	0x6f, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5e, 0x0a, 0x14, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76,
	0x31, 0x48, 0x00, 0x52, 0x12, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5e, 0x0a, 0x15, 0x72, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e,
	0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76, 0x31,
	0x48, 0x00, 0x52, 0x13, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x51,
	0x0a, 0x1a, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x69, 0x73, 0x5f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x76, 0x31, 0x12, 0x33, 0x0a, 0x02,
	0x73, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x76, 0x31, 0x52, 0x02, 0x73,
	0x63, 0x22, 0x60, 0x0a, 0x1b, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f,
	0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76, 0x31,
	0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x22, 0x65, 0x0a, 0x17, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73,
	0x63, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x76, 0x31, 0x12, 0x4a,
	0x0a, 0x09, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x74, 0x78, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2d, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x78, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x76, 0x31,
	0x52, 0x08, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x54, 0x78, 0x6e, 0x22, 0x4b, 0x0a, 0x18, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x5f, 0x76, 0x31, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x45, 0x0a, 0x18, 0x67, 0x61, 0x74, 0x65, 0x77,
	0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x65, 0x71,
	0x5f, 0x76, 0x31, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x22, 0x6e,
	0x0a, 0x22, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x5f, 0x76, 0x31, 0x12, 0x13, 0x0a, 0x05, 0x73, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x73, 0x63, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x0b, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12,
	0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x22, 0x9c,
	0x01, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x75,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6f, 0x75, 0x69, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x12, 0x35, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6e, 0x65, 0x74, 0x73, 0x22, 0x3c, 0x0a,
	0x0f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x75, 0x62, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x70, 0x75, 0x62, 0x4b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x30, 0x0a, 0x16, 0x67,
	0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72,
	0x65, 0x71, 0x5f, 0x76, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x4f, 0x0a,
	0x20, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76,
	0x31, 0x12, 0x2b, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2a, 0x70,
	0x0a, 0x0a, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x14,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x73,
	0x61, 0x62, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x69, 0x6e, 0x67, 0x10, 0x01, 0x12,
	0x16, 0x0a, 0x12, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x63,
	0x6c, 0x6f, 0x73, 0x65, 0x64, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x75, 0x74, 0x65, 0x10, 0x03,
	0x32, 0xa4, 0x02, 0x0a, 0x07, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x12, 0x47, 0x0a, 0x08,
	0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x22, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75,
	0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x69, 0x73, 0x5f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x76, 0x31, 0x1a, 0x17, 0x2e, 0x68,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x76, 0x31, 0x12, 0x41, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1f,
	0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f,
	0x73, 0x63, 0x5f, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x76, 0x31, 0x1a,
	0x17, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76, 0x31, 0x12, 0x47, 0x0a, 0x06, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x12, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x5f, 0x73, 0x63, 0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x72, 0x65,
	0x71, 0x5f, 0x76, 0x31, 0x1a, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61,
	0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x5f, 0x76, 0x31, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x44, 0x0a, 0x07, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x68,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x72, 0x65, 0x71, 0x5f, 0x76, 0x31, 0x1a, 0x17, 0x2e, 0x68,
	0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2e, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x5f, 0x76, 0x31, 0x30, 0x01, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6f, 0x75, 0x67, 0x6b, 0x69, 0x72, 0x6b, 0x6c, 0x65,
	0x79, 0x2f, 0x68, 0x65, 0x6c, 0x69, 0x75, 0x6d, 0x2d, 0x67, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x69,
	0x75, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_gateway_proto_rawDescOnce sync.Once
	file_service_gateway_proto_rawDescData = file_service_gateway_proto_rawDesc
)

func file_service_gateway_proto_rawDescGZIP() []byte {
	file_service_gateway_proto_rawDescOnce.Do(func() {
		file_service_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_gateway_proto_rawDescData)
	})
	return file_service_gateway_proto_rawDescData
}

var file_service_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_service_gateway_proto_goTypes = []interface{}{
	(CloseState)(0),                                 // 0: helium.CloseState
	(*GatewayRespV1)(nil),                           // 1: helium.gateway_resp_v1
	(*GatewayScIsValidReqV1)(nil),                   // 2: helium.gateway_sc_is_valid_req_v1
	(*GatewayScIsValidRespV1)(nil),                  // 3: helium.gateway_sc_is_valid_resp_v1
	(*GatewayScCloseReqV1)(nil),                     // 4: helium.gateway_sc_close_req_v1
	(*GatewayScCloseRespV1)(nil),                    // 5: helium.gateway_sc_close_resp_v1
	(*GatewayScFollowReqV1)(nil),                    // 6: helium.gateway_sc_follow_req_v1
	(*GatewayScFollowStreamedRespV1)(nil),           // 7: helium.gateway_sc_follow_streamed_resp_v1
	(*Routing)(nil),                                 // 8: helium.routing
	(*RoutingAddress)(nil),                          // 9: helium.routing_address
	(*GatewayRoutingReqV1)(nil),                     // 10: helium.gateway_routing_req_v1
	(*GatewayRoutingStreamedRespV1)(nil),            // 11: helium.gateway_routing_streamed_resp_v1
	(*helium.BlockchainStateChannelV1)(nil),         // 12: helium.blockchain_state_channel_v1
	(*helium.BlockchainTxnStateChannelCloseV1)(nil), // 13: helium.blockchain_txn_state_channel_close_v1
}
var file_service_gateway_proto_depIdxs = []int32{
	3,  // 0: helium.gateway_resp_v1.is_valid_resp:type_name -> helium.gateway_sc_is_valid_resp_v1
	5,  // 1: helium.gateway_resp_v1.close_resp:type_name -> helium.gateway_sc_close_resp_v1
	7,  // 2: helium.gateway_resp_v1.follow_streamed_resp:type_name -> helium.gateway_sc_follow_streamed_resp_v1
	11, // 3: helium.gateway_resp_v1.routing_streamed_resp:type_name -> helium.gateway_routing_streamed_resp_v1
	12, // 4: helium.gateway_sc_is_valid_req_v1.sc:type_name -> helium.blockchain_state_channel_v1
	13, // 5: helium.gateway_sc_close_req_v1.close_txn:type_name -> helium.blockchain_txn_state_channel_close_v1
	0,  // 6: helium.gateway_sc_follow_streamed_resp_v1.close_state:type_name -> helium.CloseState
	9,  // 7: helium.routing.addresses:type_name -> helium.routing_address
	8,  // 8: helium.gateway_routing_streamed_resp_v1.routings:type_name -> helium.routing
	2,  // 9: helium.gateway.is_valid:input_type -> helium.gateway_sc_is_valid_req_v1
	4,  // 10: helium.gateway.close:input_type -> helium.gateway_sc_close_req_v1
	6,  // 11: helium.gateway.follow:input_type -> helium.gateway_sc_follow_req_v1
	10, // 12: helium.gateway.routing:input_type -> helium.gateway_routing_req_v1
	1,  // 13: helium.gateway.is_valid:output_type -> helium.gateway_resp_v1
	1,  // 14: helium.gateway.close:output_type -> helium.gateway_resp_v1
	1,  // 15: helium.gateway.follow:output_type -> helium.gateway_resp_v1
	1,  // 16: helium.gateway.routing:output_type -> helium.gateway_resp_v1
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_service_gateway_proto_init() }
func file_service_gateway_proto_init() {
	if File_service_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayRespV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayScIsValidReqV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayScIsValidRespV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayScCloseReqV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayScCloseRespV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayScFollowReqV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayScFollowStreamedRespV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Routing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayRoutingReqV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_gateway_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayRoutingStreamedRespV1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_gateway_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*GatewayRespV1_IsValidResp)(nil),
		(*GatewayRespV1_CloseResp)(nil),
		(*GatewayRespV1_FollowStreamedResp)(nil),
		(*GatewayRespV1_RoutingStreamedResp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_gateway_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gateway_proto_goTypes,
		DependencyIndexes: file_service_gateway_proto_depIdxs,
		EnumInfos:         file_service_gateway_proto_enumTypes,
		MessageInfos:      file_service_gateway_proto_msgTypes,
	}.Build()
	File_service_gateway_proto = out.File
	file_service_gateway_proto_rawDesc = nil
	file_service_gateway_proto_goTypes = nil
	file_service_gateway_proto_depIdxs = nil
}
